/* ================================================================
   NJORD - case study copy (EN / SQ).
   Written as a pitch: the problem a prospect probably has, what NJORD
   did about it, what that means for them. Registered into the shared
   i18n store, so the existing language toggle works unchanged.
   Format: key: [english, shqip]
   ================================================================ */
import { addTranslations } from '../i18n.js';

const C = {
  /* ---- shared ---- */
  'cs.case': ['Case study', 'Studim rasti'],
  'cs.back': ['Back to work', 'Kthehu te punët'],
  'cs.scroll': ['Scroll', 'Zbrit'],
  'cs.next': ['Next case study', 'Studimi tjetër'],
  'cs.live': ['See the live site', 'Shiko faqen live'],
  'cs.start': ['Start a project', 'Nis një projekt'],
  'cs.nometrics': ['No traffic or revenue figures are claimed. This is what changed in how the business works.', 'Nuk pretendohen shifra trafiku apo të ardhurash. Kjo është ajo që ndryshoi në mënyrën si funksionon biznesi.'],
  'cs.meta.client': ['Client', 'Klienti'],
  'cs.meta.did': ['What we did', 'Çfarë bëmë'],
  'cs.meta.for': ['Built for', 'Ndërtuar për'],
  'cs.ch1': ['The problem', 'Problemi'],
  'cs.ch2': ['What we found', 'Çfarë gjetëm'],
  'cs.ch3': ['What we built', 'Çfarë ndërtuam'],
  'cs.ch4': ['For your business', 'Për biznesin tuaj'],
  'cs.you.h': ['What this does for a business like yours.', 'Çfarë bën kjo për një biznes si i juaji.'],
  'cs.you.p': ['Your customers look you up online before they call. The site either does the explaining for you, or it doesn’t.', 'Klientët tuaj ju kërkojnë online para se të telefonojnë. Faqja ose e bën shpjegimin për ju, ose jo.'],

  /* ================= VYRON ================= */
  'vy.hero.h': ['A flooring catalogue, turned into a system customers can read.', 'Një katalog dyshemesh, i kthyer në sistem që klientët e lexojnë.'],
  'vy.hero.sub': ['Premium products behind an ordinary website. We reorganised the range so it explains itself.', 'Produkte premium pas një faqeje të zakonshme. E riorganizuam gamën që të shpjegohet vetë.'],
  'vy.did': ['Information architecture, web design, development', 'Arkitekturë informacioni, dizajn web, zhvillim'],
  'vy.for': ['Flooring systems, ARDEX / Gerflor / HAFRO', 'Sisteme dyshemesh, ARDEX / Gerflor / HAFRO'],

  'vy.c1.h': ['Does this sound like your business?', 'A tingëllon si biznesi juaj?'],
  'vy.c1.1': ['Your work is better than your website makes it look.', 'Puna juaj është më e mirë se sa e shfaq faqja.'],
  'vy.c1.2': ['Visitors can’t tell what you offer without calling.', 'Vizitorët nuk e kuptojnë çfarë ofroni pa ju telefonuar.'],
  'vy.c1.3': ['To ask for a quote, they first have to understand your trade.', 'Për të kërkuar ofertë, së pari duhet ta kuptojnë profesionin tuaj.'],
  'vy.c1.ctx': ['That was VYRON. It sells and installs premium flooring systems, and its site made it look like any other installer.', 'Kjo ishte VYRON. Shet dhe instalon sisteme premium dyshemesh, dhe faqja e bënte të dukej si çdo instalues tjetër.'],

  'vy.c2.1': ['The problem was not missing information.', 'Problemi nuk ishte informacioni që mungonte.'],
  'vy.c2.2': ['The problem was how it was organised.', 'Problemi ishte si ishte i organizuar.'],
  'vy.c2.m1': ['VYRON HAD THE PRODUCTS.', 'VYRON I KISHTE PRODUKTET.'],
  'vy.c2.m2': ['WE GAVE THEM THE SYSTEM.', 'NE I DHAMË SISTEMIN.'],

  'vy.c3.h': ['Five categories. One path to a quote.', 'Pesë kategori. Një rrugë drejt ofertës.'],
  'vy.c3.p': ['Twenty-one loose terms, products and brands, sorted into the five things VYRON actually does. A visitor follows their problem to the right system instead of reading a catalogue.', 'Njëzet e një terma të shpërndarë, produkte dhe brende, të renditur në pesë gjërat që bën realisht VYRON. Vizitori ndjek problemin e tij drejt sistemit të duhur në vend që të lexojë një katalog.'],
  'vy.s.choices': ['terms to make sense of', 'terma për t’u kuptuar'],
  'vy.s.before': ['Loose terms', 'Terma të shpërndarë'],
  'vy.s.after': ['One system', 'Një sistem'],
  'vy.s.root': ['VYRON', 'VYRON'],
  'vy.cat1': ['Advanced Flooring Systems', 'Sisteme të Avancuara Dyshemesh'],
  'vy.cat2': ['Gerflor Vinyl Solutions', 'Zgjidhje Vinyl Gerflor'],
  'vy.cat3': ['HAFRO Wood Floors', 'Dysheme Druri HAFRO'],
  'vy.cat4': ['Skirtings & Transitions', 'Lajsne & Tranzicione'],
  'vy.cat5': ['On-site Finishing', 'Punime Finale në Terren'],
  'vy.t1': ['Screed', 'Screed'],
  'vy.t2': ['Self-leveling compounds', 'Përzierje vetë-nivelues'],
  'vy.t3': ['Primers', 'Primerë'],
  'vy.t4': ['Adhesives', 'Ngjitës'],
  'vy.t5': ['Waterproofing', 'Hidroizolim'],
  'vy.t6': ['ARDEX', 'ARDEX'],
  'vy.t7': ['LVT', 'LVT'],
  'vy.t8': ['Resilient floors', 'Dysheme elastike'],
  'vy.t9': ['Commercial surfaces', 'Sipërfaqe komerciale'],
  'vy.t10': ['Design surfaces', 'Sipërfaqe dizajni'],
  'vy.t11': ['Gerflor', 'Gerflor'],
  'vy.t12': ['Parquet', 'Parket'],
  'vy.t13': ['Natural wood', 'Dru natyral'],
  'vy.t14': ['HAFRO', 'HAFRO'],
  'vy.t15': ['Skirtings', 'Lajsne'],
  'vy.t16': ['Transition profiles', 'Profile tranzicioni'],
  'vy.t17': ['Silicones', 'Silikone'],
  'vy.t18': ['Grouts', 'Fugë'],
  'vy.t19': ['Joints', 'Bashkime'],
  'vy.t20': ['Sealing', 'Mbyllje'],
  'vy.t21': ['Detailing', 'Detaje'],
  'vy.f.1': ['Problem', 'Problemi'],
  'vy.f.2': ['Solution category', 'Kategoria e zgjidhjes'],
  'vy.f.3': ['Material', 'Materiali'],
  'vy.f.4': ['Application', 'Aplikimi'],
  'vy.f.5': ['Request a quote or site visit', 'Kërko ofertë ose vizitë në terren'],

  'vy.fl.h': ['Organised the way the work is done.', 'E organizuar si bëhet puna.'],
  'vy.fl.p': ['A floor is layers, each with one job, in a fixed order. The site follows the same logic.', 'Dyshemeja është shtresa, secila me një punë, në një renditje të caktuar. Faqja ndjek të njëjtën logjikë.'],
  'vy.fig.buildup': ['BUILD-UP, LAYER BY LAYER', 'STRUKTURA, SHTRESË PAS SHTRESE'],
  'vy.fig.floor': ['Floor build-up. Indicative, not to scale.', 'Struktura e dyshemesë. Orientuese, jo në shkallë.'],
  'vy.l.finish': ['FINISH', 'FINIMI'],
  'vy.l.adhesive': ['ADHESIVE', 'NGJITËSI'],
  'vy.l.leveling': ['LEVELING SYSTEM', 'NIVELIMI'],
  'vy.l.screed': ['SCREED', 'SCREED'],
  'vy.l.concrete': ['CONCRETE', 'BETONI'],

  'vy.y.1': ['Customers understand your whole range before they call.', 'Klientët e kuptojnë gamën tuaj të plotë para se të telefonojnë.'],
  'vy.y.2': ['Architects and contractors find the right system without a salesperson explaining it.', 'Arkitektët dhe kontraktorët e gjejnë sistemin e duhur pa pasur nevojë që shitësi ta shpjegojë.'],
  'vy.y.3': ['Quote requests arrive with the problem already named.', 'Kërkesat për ofertë vijnë me problemin tashmë të emërtuar.'],

  'vy.a.hero': ['Herringbone parquet in plan view, drawn in lines', 'Parket me model peshku në pamje nga lart, i vizatuar me vija'],
  'vy.a.floor': ['Floor build-up: concrete, screed, leveling system, adhesive and finish, separating layer by layer', 'Struktura e dyshemesë: beton, screed, sistem niveluese, ngjitës dhe finim, që ndahen shtresë pas shtrese'],
  'vy.a.ia': ['Twenty-one loose terms reorganising into five VYRON categories as you scroll', 'Njëzet e një terma të shpërndarë që riorganizohen në pesë kategori të VYRON ndërsa lëvizni'],

  /* ================= METALIUM ================= */
  'mt.hero.h': ['Quotes that start with the numbers.', 'Oferta që fillojnë me numrat.'],
  'mt.hero.sub': ['Inquiries arrived without what is needed to price them. We moved part of the sales process online.', 'Kërkesat vinin pa atë që duhet për t’u çmuar. E kaluam një pjesë të procesit të shitjes online.'],
  'mt.did': ['Web design, development, quote tooling', 'Dizajn web, zhvillim, mjete për ofertim'],
  'mt.for': ['Structural steel and metal fabrication', 'Konstruksione çeliku dhe përpunim metali'],

  'mt.c1.h': ['Does this sound like your business?', 'A tingëllon si biznesi juaj?'],
  'mt.c1.msg': ['How much would a 10x20 steel structure cost?', 'Sa do të kushtonte një konstruksion çeliku 10x20?'],
  'mt.mi.missing': ['missing', 'mungon'],
  'mt.mi.profile': ['Profile', 'Profili'],
  'mt.mi.dimensions': ['Dimensions', 'Përmasat'],
  'mt.mi.length': ['Length', 'Gjatësia'],
  'mt.mi.qty': ['Quantity', 'Sasia'],
  'mt.mi.weight': ['Weight', 'Pesha'],
  'mt.mi.application': ['Application', 'Përdorimi'],
  'mt.c1.1': ['Customers ask for a price without the details needed to give one.', 'Klientët kërkojnë çmim pa detajet e nevojshme për ta dhënë.'],
  'mt.c1.2': ['Your team calls each one back before the inquiry is useful.', 'Ekipi juaj e telefonon secilin përsëri para se kërkesa të bëhet e përdorshme.'],
  'mt.c1.3': ['And the site makes a serious operation look like any other shop.', 'Dhe faqja e bën një operacion serioz të duket si çdo punishte tjetër.'],
  'mt.c1.ctx': ['That was METALIUM, a structural steel and metal fabricator.', 'Kjo ishte METALIUM, prodhues konstruksionesh çeliku dhe punimesh metalike.'],

  'mt.c2.1': ['METALIUM did not need another digital brochure.', 'METALIUM nuk kishte nevojë për një broshurë tjetër digjitale.'],
  'mt.c2.2': ['It needed part of the sales process moved online.', 'Kishte nevojë që një pjesë e procesit të shitjes të kalonte online.'],
  'mt.c2.m1': ['METALIUM DIDN’T NEED ANOTHER WEBSITE.', 'METALIUM NUK KISHTE NEVOJË PËR NJË FAQE TJETËR.'],
  'mt.c2.m2': ['THEY NEEDED A DIGITAL SALES ENGINEER.', 'KISHTE NEVOJË PËR NJË INXHINIER SHITJESH DIGJITAL.'],

  'mt.c3.h': ['The customer does the first step of the quote.', 'Klienti bën hapin e parë të ofertës.'],
  'mt.c3.p': ['A steel weight calculator on the site. Profile, size, length and quantity in, theoretical weight out, and the result travels with the request.', 'Një llogaritës i peshës së çelikut në faqe. Profili, madhësia, gjatësia dhe sasia brenda, pesha teorike jashtë, dhe rezultati shkon bashkë me kërkesën.'],
  'mt.f.1': ['Customer', 'Klienti'],
  'mt.f.2': ['Select profile', 'Zgjedh profilin'],
  'mt.f.3': ['Enter dimensions', 'Fut përmasat'],
  'mt.f.4': ['Calculate weight', 'Llogarit peshën'],
  'mt.f.5': ['Add to project', 'Shton te projekti'],
  'mt.f.6': ['Request quote', 'Kërkon ofertë'],

  'mt.q.raw': ['10x20 steel hall. How much?', 'Hallë çeliku 10x20. Sa kushton?'],
  'mt.q.structure': ['STRUCTURE', 'STRUKTURA'],
  'mt.q.profile': ['PROFILE', 'PROFILI'],
  'mt.q.length': ['LENGTH', 'GJATËSIA'],
  'mt.q.qty': ['QUANTITY', 'SASIA'],
  'mt.q.weight': ['EST. WEIGHT', 'PESHA E PRITUR'],
  'mt.q.type': ['PROJECT TYPE', 'LLOJI I PROJEKTIT'],
  'mt.q.hall': ['INDUSTRIAL HALL', 'HALLË INDUSTRIALE'],
  'mt.q.cap': ['The same inquiry, before and after. Estimated weight is an example, calculated from the catalogue table.', 'E njëjta kërkesë, para dhe pas. Pesha e pritur është shembull, llogaritur nga tabela e katalogut.'],
  'mt.q.fromcalc': ['from the calculator', 'nga llogaritësi'],

  'mt.k.title': ['Try the calculator', 'Provoni llogaritësin'],
  'mt.k.family': ['Profile', 'Profili'],
  'mt.k.size': ['Size', 'Madhësia'],
  'mt.k.length': ['Length (m)', 'Gjatësia (m)'],
  'mt.k.qty': ['Quantity', 'Sasia'],
  'mt.k.weight': ['Weight', 'Pesha'],
  'mt.k.add': ['Add to project', 'Shto te projekti'],
  'mt.k.list': ['Project lines', 'Linjat e projektit'],
  'mt.k.total': ['Total', 'Gjithsej'],
  'mt.k.empty': ['Nothing added yet.', 'Ende nuk është shtuar asgjë.'],
  'mt.k.note': ['Theoretical weight from standard profile tables (EN 10365, EN 10219), without connections, plates and bolts.', 'Peshë teorike sipas tabelave standarde të profileve (EN 10365, EN 10219), pa lidhje, pllaka dhe bulona.'],
  'mt.k.sent': ['This list is what arrives with the quote request.', 'Kjo listë vjen bashkë me kërkesën për ofertë.'],
  'mt.k.open': ['Open the full calculator on the METALIUM site', 'Hap llogaritësin e plotë në faqen e METALIUM'],
  'mt.k.remove': ['Remove', 'Hiq'],
  'mt.k.badinput': ['Enter a length and a quantity.', 'Shkruani gjatësinë dhe sasinë.'],

  'mt.p.h': ['Plain categories. Technical language intact.', 'Kategori të qarta. Gjuha teknike e paprekur.'],
  'mt.p.cap': ['The profiles contractors and engineers expect, kept by name and drawn to standard conventions.', 'Profilet që presin kontraktorët dhe inxhinierët, të ruajtura me emër dhe të vizatuara sipas konventave standarde.'],

  'mt.y.1': ['Inquiries arrive with profile, size, length and quantity.', 'Kërkesat vijnë me profilin, madhësinë, gjatësinë dhe sasinë.'],
  'mt.y.2': ['Your team starts from a technical request, not a question.', 'Ekipi juaj fillon nga një kërkesë teknike, jo nga një pyetje.'],
  'mt.y.3': ['Your site reads as the engineering operation you are.', 'Faqja juaj lexohet si operacioni inxhinierik që jeni.'],

  'mt.a.hero': ['IPE 200 steel section with dimension lines', 'Prerja e çelikut IPE 200 me vija përmasash'],
  'mt.a.ipe': ['IPE 200 section drawing', 'Vizatim i prerjes IPE 200'],
  'mt.a.hea': ['HEA 200 section drawing', 'Vizatim i prerjes HEA 200'],
  'mt.a.heb': ['HEB 200 section drawing', 'Vizatim i prerjes HEB 200'],
  'mt.a.upn': ['UPN 200 section drawing', 'Vizatim i prerjes UPN 200'],
  'mt.a.tube': ['Square tube 100 by 4 section drawing', 'Vizatim i prerjes së tubit katror 100 me 4'],
};

addTranslations(Object.fromEntries(Object.entries(C).map(([k, [en, sq]]) => [k, { en, sq }])));
